#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["disable_audio_stream_wav"]:
    # Exclude audio_effect_record.cpp when AudioStreamWAV is disabled
    import glob
    import os
    cpp_files = glob.glob(os.path.join(str(Dir(".").srcnode()), "*.cpp"))
    cpp_files = [os.path.basename(f) for f in cpp_files if "audio_effect_record" not in f]
    for f in cpp_files:
        env.add_source_files(env.servers_sources, f)
else:
    env.add_source_files(env.servers_sources, "*.cpp")
