#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["disable_video_stream_player"]:
    # Exclude video_stream_player.cpp when disabled
    import glob
    import os
    cpp_files = glob.glob(os.path.join(str(Dir(".").srcnode()), "*.cpp"))
    cpp_files = [os.path.basename(f) for f in cpp_files if "video_stream_player" not in f]
    for f in cpp_files:
        env.add_source_files(env.scene_sources, f)
else:
    env.add_source_files(env.scene_sources, "*.cpp")
