#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["disable_multiplayer"] or env["disable_http_request"]:
    # Exclude files when disabled
    import glob
    import os
    cpp_files = glob.glob(os.path.join(str(Dir(".").srcnode()), "*.cpp"))
    exclude_patterns = []
    if env["disable_multiplayer"]:
        exclude_patterns.append("multiplayer")
    if env["disable_http_request"]:
        exclude_patterns.append("http_request")
    cpp_files = [os.path.basename(f) for f in cpp_files if not any(pattern in f for pattern in exclude_patterns)]
    for f in cpp_files:
        env.add_source_files(env.scene_sources, f)
else:
    env.add_source_files(env.scene_sources, "*.cpp")
